message("Building fixed income executable module")

source("scripts/domain_discovery.R")

ensure_dir <- function(path) {
  if (!dir.exists(path)) dir.create(path, recursive = TRUE)
}

read_scalar <- function(path, prefix) {
  lines <- readLines(path, warn = FALSE)
  hit <- lines[grepl(prefix, lines, fixed = TRUE)]
  if (length(hit) == 0) return(NA_character_)
  trimws(sub(prefix, "", hit[[1]], fixed = TRUE))
}

object_title <- function(object_id) {
  read_scalar(file.path("objects", object_id, "metadata.yaml"), "title:")
}

objects <- discover_objects()
module_dir <- "generated/module/fixed_income_module_v1"
ensure_dir(module_dir)
ensure_dir(file.path(module_dir, "objects"))
ensure_dir(file.path(module_dir, "packages"))
ensure_dir("reports")

object_rows <- c()
for (object_id in objects) {
  title <- object_title(object_id)
  object_rows <- c(object_rows, paste0("    - id: ", object_id, "\n      title: ", title, "\n      status: compiled"))

  object_out <- file.path(module_dir, "objects", paste0(object_id, ".yaml"))
  writeLines(c(
    "compiled_object:",
    paste0("  id: ", object_id),
    paste0("  title: ", title),
    "  source: Canonical Academic Object",
    paste0("  blueprint: generated/blueprints/", object_id, "_blueprint.json"),
    paste0("  air: generated/air/", object_id, "_air.json"),
    paste0("  assets: generated/assets/", object_id),
    "  status: compiled"
  ), object_out)
}

# Package registration. FI-DER-0009 creates LU001.
lu001_dir <- "generated/packages/LU001"
lu001_status <- ifelse(dir.exists(lu001_dir), "compiled", "missing")

writeLines(c(
  "module:",
  "  id: FIXED-INCOME-MODULE-V1",
  "  title: Valoracion de Activos Financieros - Renta Fija",
  "  domain: fixed_income",
  "  release: FI-DER-0010",
  "  status: compiled",
  paste0("  canonical_objects: ", length(objects)),
  "  learning_packages:",
  paste0("    - id: LU001\n      title: Institutional Investment Ecosystem\n      status: ", lu001_status),
  "  objects:",
  object_rows
), file.path(module_dir, "module_manifest.yaml"))

index <- c(
  "# Fixed Income Module v1",
  "",
  "Generated by AOS Fixed Income Domain FI-DER-0010.",
  "",
  "## Canonical Academic Objects",
  ""
)
for (object_id in objects) {
  index <- c(index, paste0("- ", object_id, " — ", object_title(object_id)))
}
index <- c(index, "", "## Learning Packages", "", paste0("- LU001 — Institutional Investment Ecosystem: ", lu001_status))
writeLines(index, file.path(module_dir, "README.md"))
writeLines(index, file.path(module_dir, "index.md"))

writeLines(c(
  "module_build_report:",
  "  release: FI-DER-0010",
  "  status: PASS",
  paste0("  canonical_objects: ", length(objects)),
  paste0("  lu001_status: ", lu001_status),
  paste0("  output: ", module_dir)
), "reports/module_build_report.yaml")

message("Wrote ", module_dir)
message("Wrote reports/module_build_report.yaml")
