message("Generating fixed income academic assets")

source("scripts/domain_discovery.R")

read_text <- function(path) {
  if (!file.exists(path)) return(character())
  readLines(path, warn = FALSE, encoding = "UTF-8")
}

extract_scalar <- function(path, key, default = "") {
  lines <- read_text(path)
  pattern <- paste0("^", key, ":")
  hit <- grep(pattern, lines, value = TRUE)
  if (length(hit) == 0) return(default)
  trimws(sub(pattern, "", hit[[1]]))
}

extract_yaml_list_after <- function(path, section_key) {
  lines <- read_text(path)
  start <- grep(paste0("^  ", section_key, ":"), lines)
  if (length(start) == 0) return(character())
  start <- start[[1]]
  following <- lines[(start + 1):length(lines)]
  stop_at <- grep("^  [A-Za-z0-9_]+:", following)
  if (length(stop_at) > 0) {
    following <- following[seq_len(stop_at[[1]] - 1)]
  }
  values <- trimws(sub("^- ", "", trimws(following[grepl("^    - ", following)])))
  values[nzchar(values)]
}

count_pattern <- function(path, pattern) {
  lines <- read_text(path)
  sum(grepl(pattern, lines, fixed = TRUE))
}

extract_ids <- function(path, prefix) {
  lines <- read_text(path)
  hits <- grep(paste0("    - id: ", prefix), lines, value = TRUE)
  trimws(sub(".*id: ", "", hits))
}

render_asset <- function(object_id, asset_name, title) {
  object_dir <- file.path("objects", object_id)
  metadata <- file.path(object_dir, "metadata.yaml")
  knowledge <- file.path(object_dir, "knowledge.yaml")
  professional <- file.path(object_dir, "professional.yaml")
  learning <- file.path(object_dir, "learning.yaml")
  evidence <- file.path(object_dir, "evidence.yaml")

  knowledge_units <- count_pattern(knowledge, "    - id: K")
  competencies <- count_pattern(professional, "    - id: PC")
  decisions <- count_pattern(professional, "    - id: PD")
  capabilities <- count_pattern(learning, "    - id: LC")

  required_assets <- extract_yaml_list_after(learning, "required_assets")
  if (length(required_assets) == 0) {
    required_assets <- c("slides", "workshop", "instructor_guide", "student_guide", "exercises", "solutions", "rubric", "dgpi")
  }

  header <- c(
    paste0("# ", title),
    "",
    paste0("Academic Object: ", object_id),
    paste0("Asset: ", asset_name),
    "Generated by: FI-DER-0008 Asset Generator",
    "",
    "## Object Metrics",
    "",
    paste0("- Knowledge units: ", knowledge_units),
    paste0("- Professional competencies: ", competencies),
    paste0("- Professional decisions: ", decisions),
    paste0("- Learning capabilities: ", capabilities),
    "",
    "## Canonical Source",
    "",
    "This asset is generated from the canonical academic object package. Manual edits should be made in the object source files, not in generated assets.",
    ""
  )

  body <- switch(asset_name,
    slides = c(
      "## Slide Outline",
      "",
      "1. Institutional context and object purpose.",
      "2. Core knowledge units.",
      "3. Professional decisions supported by the object.",
      "4. Learning capabilities and classroom applications.",
      "5. DGPI connection and assessment evidence."
    ),
    workshop = c(
      "## Workshop Structure",
      "",
      "Students analyze a realistic institutional case, identify the relevant mandate, map constraints, and produce professional evidence aligned with the object."
    ),
    instructor_guide = c(
      "## Instructor Guide",
      "",
      "Use the knowledge layer for conceptual exposition, the professional layer for applied discussion, and the learning layer for classroom sequencing."
    ),
    student_guide = c(
      "## Student Guide",
      "",
      "Focus on connecting institutional context, fixed income decisions, and observable professional outputs."
    ),
    exercises = c(
      "## Exercises",
      "",
      "1. Define the key concepts introduced by this object.",
      "2. Map each competency to a professional decision.",
      "3. Apply the object to a realistic fixed income institutional case."
    ),
    solutions = c(
      "## Solutions",
      "",
      "Solutions should demonstrate consistency between the knowledge package, the professional decision criteria, and the learning evidence."
    ),
    rubric = c(
      "## Rubric",
      "",
      "| Criterion | Excellent | Satisfactory | Needs Work |",
      "|---|---|---|---|",
      "| Conceptual accuracy | Complete and precise | Mostly correct | Incomplete |",
      "| Professional mapping | Clear and justified | Partially justified | Weak mapping |",
      "| Evidence quality | Decision-ready | Usable | Insufficient |"
    ),
    dgpi = c(
      "## DGPI Link",
      "",
      "The DGPI requires students to transform the canonical knowledge and professional decisions into an integrated applied deliverable."
    ),
    toolbox = c(
      "## Toolbox",
      "",
      "No numerical toolbox dependency is required for this object unless specified by later quantitative objects."
    ),
    c("## Asset Body", "", "Generated asset placeholder governed by the institutional asset policy.")
  )

  c(header, body, "")
}

generate_assets_for_object <- function(object_id) {
  object_dir <- file.path("objects", object_id)
  metadata <- file.path(object_dir, "metadata.yaml")
  learning <- file.path(object_dir, "learning.yaml")
  title <- extract_scalar(metadata, "title", object_id)

  assets <- extract_yaml_list_after(learning, "required_assets")
  if (length(assets) == 0) {
    assets <- c("slides", "workshop", "instructor_guide", "student_guide", "exercises", "solutions", "rubric", "dgpi")
  }
  if (!"toolbox" %in% assets) assets <- c(assets, "toolbox")

  out_dir <- file.path("generated", "assets", object_id)
  dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

  for (asset in assets) {
    out <- file.path(out_dir, paste0(asset, ".md"))
    writeLines(render_asset(object_id, asset, title), out, useBytes = TRUE)
  }

  message("Wrote generated assets for ", object_id)
}

objects <- discover_objects()
for (object_id in objects) {
  generate_assets_for_object(object_id)
}

report <- c(
  "asset_generation_report:",
  "  release: FI-DER-0008",
  paste0("  objects: ", length(objects)),
  "  status: GENERATED",
  "  generated_root: generated/assets"
)

dir.create("reports", recursive = TRUE, showWarnings = FALSE)
writeLines(report, "reports/asset_generation_report.yaml")
message("Wrote reports/asset_generation_report.yaml")
