message("Validating generated academic assets")

source("scripts/domain_discovery.R")

required_assets <- c(
  "slides.md",
  "workshop.md",
  "instructor_guide.md",
  "student_guide.md",
  "exercises.md",
  "solutions.md",
  "rubric.md",
  "dgpi.md",
  "toolbox.md"
)

contains_text <- function(path, text) {
  any(grepl(text, readLines(path, warn = FALSE, encoding = "UTF-8"), fixed = TRUE))
}

validate_assets_for_object <- function(object_id) {
  out_dir <- file.path("generated", "assets", object_id)
  required_paths <- file.path(out_dir, required_assets)
  missing <- required_paths[!file.exists(required_paths)]
  if (length(missing) > 0) {
    stop(paste("Missing generated assets for", object_id, ":", paste(missing, collapse = ", ")), call. = FALSE)
  }

  checks <- vapply(required_paths, contains_text, logical(1), text = "Generated by: FI-DER-0008 Asset Generator")
  if (!all(checks)) {
    stop(paste0(object_id, " asset validation checks failed"), call. = FALSE)
  }

  message(object_id, " asset validation: PASS")
}

objects <- discover_objects()
for (object_id in objects) {
  validate_assets_for_object(object_id)
}

if (!file.exists("reports/asset_generation_report.yaml")) {
  stop("Missing reports/asset_generation_report.yaml", call. = FALSE)
}

message("Domain asset validation: PASS")
